#!/bin/sh
if [ $BASH_VERSION ]
then
    # It means bash is started as a login shell
    . ~/.bashrc
else
    # It means .profile is executed during X's startup process
    . ~/.shrc
fi

export PATH=/home/btquanto/Programs/sencha/Sencha/Cmd/5.1.2.52:$PATH

export SENCHA_CMD_3_0_0="/home/btquanto/Programs/sencha/Sencha/Cmd/5.1.2.52"
